import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main>
          <div className="max-w-2xl mx-auto mt-8">
            <h1 className="text-balance scroll-m-20 text-2xl mb-6 font-semibold tracking-tight">
              Integrating Next.js with a backend server using an auth provider
            </h1>
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
